### ISSUE TITLE
Australian Radio Talkback Corpus (ART)

### ISSUE THREAD

**Issue by iamyifan** [southern-cross-ai/ART#1]

**Comment by msgrewal** [comment]
Assigned to Gillian.

**Comment by iamyifan** [comment]
Thank you @GillianLaw for cleaning the data 🥳
I modified a little based on Gillian's work and preparing for launching Hugging Face.

**Comment by iamyifan** [comment]
Uploaded to Hugging Face ; )

**Comment by iamyifan** [comment]
Finished all work. Set to inactive. Will reopen if is has any future demands.
